apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: helloworld
  name: helloworld
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      run: helloworld
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: helloworld
    spec:
      containers:
      - image: ryutah/python-gke-sample:0.0.2
        name: app
        ports:
        - containerPort: 8080
          name: httpport
        readinessProbe:
          httpGet:
            path: /
            port: httpport
          initialDelaySeconds: 3
          periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  labels:
    run: helloworld
  name: helloworld
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: helloworld
  type: LoadBalancer

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: helloworld
  namespace: default
spec:
  maxReplicas: 5
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: helloworld
  targetCPUUtilizationPercentage: 80
